# Generated by Django 4.0.5 on 2022-08-06 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)])),
                ('surname', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(1)])),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
