# Generated by Django 4.0.5 on 2022-07-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0002_ferry_time_arrival_ferry_time_departure"),
    ]

    operations = [
        migrations.AddField(
            model_name="ferry",
            name="port_arrival",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="ferry",
            name="port_departure",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
