# Generated by Django 4.0.5 on 2022-07-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_ferry_port_arrival_ferry_port_departure'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferry',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ferry',
            name='time_arrival',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ferry',
            name='time_departure',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
