# Generated by Django 4.0.5 on 2022-07-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timetable", "0005_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="port",
            name="boat",
            field=models.ManyToManyField(to="timetable.ferry"),
        ),
    ]
