# Generated by Django 4.0.5 on 2022-08-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_port_boat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='boat',
            field=models.ManyToManyField(null=True, to='timetable.ferry'),
        ),
    ]
